import Head from "next/head";
import ContactSection from "../components/ContactSection";
import About from "../components/About";
import { motion } from "framer-motion";
import styled from "styled-components";

const AboutFooter = styled.footer`
  display: none;

  @media only screen and (max-width: 600px) {
    display: block;
  }
`;

export const Title = styled.h2`
  font-size: 45px;
  color: black;
  margin-top: 55px;
  margin-left: 255px;
  padding: 30px 40px 30px 300px;
  background: teal;
  color: #fff;
  text-shadow: 1px 1px 1px rgb(0, 123, 165);
  text-align: right;

  @media only screen and (max-width: 1024px) {
    margin: auto;
    padding-top: 100px;
  }

  @media only screen and (max-width: 600px) {
    font-size: 35px;
    background: none;
    margin: 0;
    padding-top: 50px;
    padding-bottom: 0px;
    padding-right: 20px;
    color: #000;
    text-shadow: none;
  }
`;

const contact = () => {
  return (
    <>
      <Head>
        <title>Elsa Hovey | Contact</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <motion.div
        initial={{ opacity: 0 }}
        animate={{ opacity: 1 }}
        transition={{ delay: 0.3, duration: 0.5 }}
      >
        <Title>Contact</Title>
        <ContactSection />

        <AboutFooter id="about-mobile">
          <About />
        </AboutFooter>
        {/* <ContactSection /> */}
      </motion.div>
    </>
  );
};

export default contact;
