import Head from "next/head";
import ContactSection from "../components/ContactSection";
import { motion } from "framer-motion";

const contact = () => {
  return (
    <>
      <Head>
        <title>Elsa Hovey- Development/ Design</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <motion.div
        initial={{ opacity: 0 }}
        animate={{ opacity: 1 }}
        transition={{ delay: 0.3, duration: 0.5 }}
      >
        <ContactSection />
      </motion.div>
    </>
  );
};

export default contact;
