import Head from "next/head";
import ContactSection from "../components/ContactSection";
import About from "../components/About";
import { motion } from "framer-motion";
import styled from "styled-components";

const AboutFooter = styled.footer`
  display: none;

  @media only screen and (max-width: 600px) {
    display: block;
  }
`;

const contact = () => {
  return (
    <>
      <Head>
        <title>Elsa Hovey- Development/ Design</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <motion.div
        initial={{ opacity: 0 }}
        animate={{ opacity: 1 }}
        transition={{ delay: 0.3, duration: 0.5 }}
      >
        <AboutFooter id="about-mobile">
          <About />
        </AboutFooter>
        <ContactSection />
      </motion.div>
    </>
  );
};

export default contact;
