/* eslint-disable @next/next/no-img-element */
import Head from "next/head";
import Link from "next/link";
import Services from "../components/Services";
import styled from "styled-components";
import { motion } from "framer-motion";

//STYLES
const Wrapper = styled.div``;

export const Quote = styled.div`
  opacity: 0.8;
  background: teal;
  padding: 35px;
  grid-area: rs;
  margin-top: 40px;
  margin-left: 60px;
  h4 {
    font-size: 30px;
    color: #000;
  }
  p {
    font-size: 24px;
    color: #000;
  }
  a {
    color: #000;
    text-decoration: underline;
    margin: 5px;
  }
  a:hover {
    color: aquamarine;
    transition: 2s;
  }

  @media only screen and (max-width: 1024px) {
    margin-left: 30px;
    h4 {
      font-size: 27px;
    }
    p {
      font-size: 20px;
    }
  }

  @media only screen and (max-width: 834px) {
    margin-left: 90px;
    margin-top: 50px;
  }
  @media only screen and (max-width: 768px) {
    margin-left: 50px;
    // margin-top: 50px;
  }

  @media only screen and (max-width: 600px) {
    // margin-left: 70px;
    margin-top: 40px;
  }
`;

//END STYLES

export default function Home() {
  return (
    <>
      <Head>
        <title>Elsa Hovey- Development/ Design</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Wrapper>
        <motion.div
          initial={{ opacity: 0 }}
          animate={{ opacity: 1 }}
          transition={{ delay: 0.3, duration: 0.5 }}
        >
          <Quote>
            <h4>
              Hi there,
              <Link href="/#about">Im Elsa.</Link>
            </h4>
            <p>
              Im a web developer based in Joshua Tree, CA. I create niche
              websites and solutions for small business owners and creatives.{" "}
            </p>
          </Quote>

          <Services />
        </motion.div>
      </Wrapper>
    </>
  );
}
