/* eslint-disable @next/next/no-img-element */
import Head from "next/head";
import { sanityClient, urlFor } from "../client";
import styled from "styled-components";
import { motion } from "framer-motion";
import JtPic from "../public/images/joshuatreeabout.jpg";
import Image from "next/image";

const Home = ({ posts }) => {
  return (
    <>
      <Head>
        <title>The Laughing Coyote</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <motion.div
        initial={{ opacity: 0 }}
        animate={{ opacity: 1 }}
        transition={{ delay: 0.3, duration: 0.5 }}
      ></motion.div>
      <div>
        <h2>Info</h2>
        Lorem ipsum dolor sit amet consectetur adipisicing elit. Optio similique
        itaque quam impedit assumenda, ipsa porro beatae. Natus veritatis
        facilis fugiat saepe, quisquam maxime impedit iure voluptatibus
        consequuntur, molestias unde.
      </div>
      <ul>
        <li>Services Includes</li>
        <li>Package Rate</li>
        <li>Page Options</li>
        <li></li>
      </ul>
    </>
  );
};

export default Home;
